In [4]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn as sl
%matplotlib inline
import scipy as sc
import math as ma
from scipy import linalg, optimize, constants, interpolate, special, stats
from math import exp, pow, sqrt, log

import seaborn as sns #spezielle Graphikdarstellungen
import statsmodels.api as sm
import statsmodels.stats.api as sms

# 1.) Erste Schritte

Python kann aus der Konsole direkt benutzt werden.  
Befehle werden dann direkt eingegeben bzw. Skripte, die z.B. in einem Texteditor erstellt wurden können aufgerufen und ausgeführt werden.  
Übersichtlicher ist es jedoch eine Notebook-Umgebung zu benutzen. Wir benutzen Jupyter als Notebook-Umgebung.

## 1.1) Installation von Jupyter

Wenn Sie eine Python Installation auf Ihrem Rechner durchgeführt haben sollten Sie zunächst den Python-Installer PIP installieren.  
PIP kann benutzt werden um alle notwendigen Python-Pakete aus der Konsole zu installieren. PIP ist normalerweise bei der Python Installation mit enthalten. Um mit der neuesten verfügbaren Version arbeiten zu können sollten Sie ein upgrade (Konsole) ausführen:  

WINDOWS: python -m pip install -U pip setuptools  
Mac oder LINUX: pip install -U pip setuptools  

Jupyter installieren Sie dann ganz einfach mit dem Befehl:  

Python2: pip install jupyter
->(Python3: pip3 install jupyter)  

Jedes andere Zusatzpaket läßt sich mit Hilfe von PIP mit dem Befehl  

pip install "Paketname" nachinstallieren.  

Jupyter starten Sie aus der Konsole mit dem Befehl:  
jupyter notebook
 

## 1.2) Rechnen mit Python

in den Kommandozeilen können Sie direkt Variablen definieren und Rechenoperationen ausführen.  
Kommentare können Sie mit Hilfe des Symbols # einfügen um den Code zu dokumentieren.

Die Zelle wird ausgeführt, wenn sie das "Play"-Symbol in der Tool-bar drücken.  
Hier finden sich auch - von rechts nach links - "save", "add cell below", "cut selcted cell", etc.
 

...ein erstes Beispiel

In [2]:
a = 1 #definiere die Variable a und weise den Wert 1 zu
b = 2 #definiere die Variable b und weise den Wert 2 zu c = a**2+b**2 #berechne die Summe aus a^2 und b^2
c = a**2 + b**2

die Zelle ist nun ausgewertet.  
Standardmäßig wird die Ausgabe unterdrückt. Wenn man das Ergebnis z.B. für c sehen will muß dies eingegeben werden

In [3]:
c

5

Python hat verschiedene Zahlenformate:
- int
- float
- complex

In [4]:
type(c) #Integer


int

In [5]:
a = 1.5 + 0.5j #Komplexe Zahlen
type(a)

complex

In [6]:
a.real #Realteil

1.5

In [7]:
a.imag #Imaginärteil

0.5

In [8]:
d = 2. #Float                                                               

In [9]:
type(d)

float

In [10]:
3 > 4 #Boolesche Operatoren 
test = (3 > 4)

test 

False

In [11]:
type(test)

bool

Das Jupyter Notebook kann wie ein Taschenrechner benutzt werden.  
Arithmetische Operationen +, -, *, /, %


In [12]:
2/3

0.6666666666666666

### Aufgabe 1: 
Definieren Sie eine komplexe Zahl. Berechnen Sie Realteil, Imaginärteil und geben Sie das Ergebnis in unterschiedlichen Zahlenformaten aus.
            

In [8]:
comp = 3.1415 + 2j
print(type(comp.real))

<class 'float'>


## 1.3) Funktionen in Python

Zunächst wird die Bezeichnung der Funktion angelegt und die Variablen werden festgelegt.  
Danach wird die Abbildungsvorschrift definiert.  
Zu beachten ist, daß eine Einrückung nötig ist.
                           

In [13]:
def disk_area(radius): #definiere die Kreisfläche als Funktion des Radius 
    return 3.14 * radius * radius #Abbildungsvorschrift

In [14]:
disk_area(1.5)

7.0649999999999995

In [15]:
def double(x):
     return 2*x

In [16]:
double(3.)

6.0

### Aufgabe 2: 
    
Definieren Sie die Funktion  

$f(x,y)=2+x^2+3y^2$

Werten Sie die Funktion an verschiedenen Punkten (x,y) aus.
           

In [11]:
def func(x, y):
    return 2 + x**2 + 3*y**2

print(func(2, 5))

81


## 1.4) Spezielle Funktionen

Dazu kann beispielweise das Python Paket "math" benutzt werden.  
Spezielle Funktionsdefinitionen müssen vor der Anwendung aus dem Paket math geladen werden.
                          

In [12]:
from math import exp, pow, sqrt, log

In [13]:
exp(3) # e**x

20.085536923187668

In [14]:
pow(2,3) #x**y hier 2**3

8.0

In [15]:
sqrt(9) #Wurzel x

3.0

In [21]:
log(2) #Logarithmus zur Basis e - natürlicher Logarithmus

0.6931471805599453

In [22]:
log(2,10) #Logarithmus zu beliebiger Basis - hier zur Basis 10

0.30102999566398114

Trigonometrische Funktionen (Argument in rad)

In [16]:
from math import cos, sin, tan

In [24]:
cos(3.14)

-0.9999987317275395

In [25]:
sin(3.14)

0.0015926529164868282

In [26]:
tan(-2*3.14)

0.003185317952531891

...man kann rad in Grad umrechnen und umgekehrt...

In [27]:
from math import degrees, radians

In [28]:
degrees(3.141592653589793) #berechne Pi in Grad

180.0

In [29]:
radians(180) #berechne 180° in rad

3.141592653589793

Wichtige mathematische Zahlen können auch als Symbole importiert werden

In [30]:
from math import pi, e

In [31]:
pi #Kreiszahl Pi

3.141592653589793

In [32]:
e #transzendente Zahl e

2.718281828459045

In [33]:
sin(pi) #sin(Pi) als float

1.2246467991473532e-16

In [34]:
int(sin(pi)) #sin(pi) als Integer

0

In [35]:
cos(pi/2) #cos(Pi/2) als float

int(cos(pi/2)) #als Integer

0

verfügbare trigonometrische Funktionen: 

- cos(x)
- sin(x)
- tan(x) 
- acos(x) (arc cos) 
- asin(x) (arc sin)
- atan(x) (arc tan)

hyperbolische Varianten:  
    
- cosh(x)
- sinh(x)
- tanh(x)
- acosh(x)
- asinh(x)
- atanh(x)  

### Aufgabe 3:  

- Definieren Sie eine Funktion, die den Betrag einer komplexe Zahl berechnet und testen Sie die Funktion an einem Beispiel.
- Definieren Sie zwei Funktionen, die den Winkel zwischen zwei Vektoren (a1,a2) und (b1,b2) im ersten Quadranten einmal in rad und einmal in Grad berechnen.  
- Wenden Sie die Funktionen auf die Vektoren (0,1), (1,1) an.
- Definieren Sie eine Funktion, die den Abstand von zwei Punkten im R^2 berechnet.  
- Wenden Sie die Funktion auf (0,1) und (1,0) an.

In [36]:
from math import acos
def rad_winkel(a1,a2,b1,b2):
         return acos((a1*b1+a2*b2)/(sqrt(a1**2+a2**2)*sqrt(b1**2+b2**2)))
                               

In [37]:
a = rad_winkel(0,1,1,1) 
a                               

0.7853981633974484

In [38]:
from math import acos, degrees 

def grad_winkel(a1,a2,b1,b2):
         return degrees(acos((a1*b1+a2*b2)/(sqrt(a1**2+a2**2)*sqrt(b1**2+b2**2))))
                               

In [39]:
a = grad_winkel(0,1,1,1) 
a

45.00000000000001

In [40]:
def abstand(a1,a2,b1,b2):
     return sqrt((-a1+b1)**2+(-a2+b2)**2)

In [41]:
a = abstand(0,1,1,0)
a

1.4142135623730951

# 2) Arrays – NumPy

Das Paket NumPy ist eine Python-Erweiterung, die bsonders geeignet ist um mit Matrizen (arrays) umzugehen.  
Es erlaubt auch mit multi-dimensionalen arrays umzugehen.  
Vorteile:
    
- näher an der hardware (efficiency)
- designed für "scientific computation"
- array orientiertes Rechnen

Das Paket muß zunächst geladen werden um alle Funktionalitäten nutzen zu können...    
Die empfohlene Art NumPy zu importieren ist:  
"import numpy as np"  

-> theoretisch können Sie aber auch einen anderen Namen vergeben  
(nicht so geschickt, wenn Sie Code z.B. aus dem Netz verwenden/recyceln wollen, weil dort meistens von dieser Konvention ausgegangen wird) 

-> Ähnliches gilt für andere Pakete wie z.B. Pandas (dazu später mehr...)
                                         

In [17]:
import numpy as np

In [43]:
a = np.array([0, 1, 2, 3]) #definiere ein Numpy array, das die Zahlen 0,1,2,3 enthält
a

array([0, 1, 2, 3])

Arrays können enthalten:  
    
- Daten aus Experimenten/Simulationen bei diskreten Zeitschritten
- Signale aufgezeichnet von Meßinstrumenten, z.B. sound wave
- Pixel eines Bildes, grey-level oder Farbe
- 3-D Daten gemessen an unterschiedlichen X-Y-Z Positionen, z.B. MRI scan
- ...
mit np.array? können Sie die Doku zum Array in NumPy aufrufen...
                                            

In [18]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

## 2.1) Manuelle Erzeugung von Arrays  

- 1-D:

In [22]:
a = np.array([0, 1, 2, 3]) 
a

TypeError: Field elements must be 2- or 3-tuples, got '9'

In [20]:
a.ndim #Dimension ausgeben

1

In [21]:
len(a) #Länge

4

In [48]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array

In [49]:
b.ndim #Dimensions

2

In [50]:
b.shape #Form

(2, 3)

In [51]:
len(b) # gibt die Größe der ersten Dimension aus

2

In [52]:
a.shape #genauere Infos zur Struktur

(4,)

Arrays in 2-D, 3-D, ...:

In [53]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
b.shape
b.ndim
len(b)

2

In [55]:
c = np.array([[[1], [2]], [[3], [4]]]) #komplexeres Array 
c

array([[[1],
        [2]],

       [[3],
        [4]]])

## 2.2) Methoden zur Erzeugung von Arrays  

Normalerweise wird man in den seltensten Fällen die Einträge eines Arrays per Hand definieren.  
Entweder werden Daten eingelesen oder man generiert spezielle Arrays. Hier einige Beispiele:
              

### 2.2.1) ganzzahlige Einträge

In [56]:
a = np.arange(10) # 0 .. n-1 (!) - Achtung Python begint immer bei 0 zu zählen!!!
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b = np.arange(1, 9, 2) # start, end (exclusive), Schrittweite b

### 2.2.2) definiert durch Anzahl der Punkte in einem Intervall

In [58]:
c = np.linspace(0, 1, 6) # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [59]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

### 2.2.3) spezielle Arrays

In [60]:
a = np.ones((3, 3)) # reminder: (3, 3) is a tuple - voll besetztes Array mit 1-Einträgen 
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
b = np.zeros((2, 2)) #voll besetztes Array mit 0-Einträgen b

In [62]:
c = np.eye(3) #Einheitsmatrix als Array- Identität 
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
d = np.diag(np.array([1, 2, 3, 4])) #Array mit Diagonale mit vordefinierten Einträgen d

### 2.2.4.) Arrays mit Zufallszahlen

In [64]:
a = np.random.rand(4) # uniform in [0, 1] - Zufallszahlen aus Uniformer Verteilung a
a

array([0.80563943, 0.23056404, 0.75295078, 0.76475405])

In [65]:
b = np.random.randn(4) # Normalveteilung
b

array([-0.29382647, -0.17747532,  0.76984068,  1.87615855])

In [66]:
np.random.seed(1234) # Setting the random seed - macht die erzeugten Zufallszahlen reproduzierbar

### Aufgabe 4: Erzeugung von Arrays mit Hilfe bestimmter Funktionen  

- Experimentieren Sie mit arange, linspace, ones, zeros, eye und diag.
- Erzeugen Sie verschiedene Arrays mit Zufallszahlen.
- Setzen Sie den seed bevor Sie ein Array mit Zufallszahlen erzeugen.
- Testen Sie die Funktion np.empty. Was passiert? Wann könnte das nützlich sein?

In [67]:
a = np.array([1, 2, 3]) #Datentypen im Array können abgefragt werden mit dtype - default Integer, wenn so eingegeben
a.dtype

dtype('int64')

In [68]:
c = np.array([1, 2, 3], dtype=float) #Datentyp kann explizit spezifiziert werden 
c.dtype

dtype('float64')

Der default Datentyp ist float:

In [26]:
a = np.ones((3, 3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Rechenoperationen werden bei arrays elementweise ausgeführt (Achtung: Dimensionen müssen zusammenpassen!!)

In [27]:
 
a = np.ones((3, 3))
b = np.diag(np.array([1, 2, 3])) #Array mit Diagonale mit vordefinierten Einträgen b

c = a*2 #Multiplikation mit Skalar
a+b #Addition elementweise
b*c #Multiplikation elemtweise
2*a+(b*c) #zusammengesetzte Operation
print(c)


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### Aufgabe 5:  

Berechnen Sie für a = np.ones((3, 3)) und b = np.diag(np.array([1, 2, 3, 4])) das elementweise Produkt a*b.

## 2.3) Die NumPy Matrix Klasse - ein spezielles 2D Array numpy.matrix  

"Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power.

In [71]:
A = np.matrix('1 2; 3 4') #2x2 Matrix mit speziellen Einträgen
A

matrix([[1, 2],
        [3, 4]])

In [72]:
print(A) #gibt nur die Elemente aus

[[1 2]
 [3 4]]


In [73]:
np.matrix([[1, 2], [3, 4]]) #andere Möglichkeit die Matrix zu definieren

matrix([[1, 2],
        [3, 4]])

In [74]:
A = np.matrix('1 2; 3 4') #definiere zwei Matrizen
B = np.matrix('5 6; 7 8')
A*B #berechne das Matrizenprodukt

matrix([[19, 22],
        [43, 50]])

Für die Matrixklasse gibt es viele Sonderfunktionen wie z.B. Transponierte bilden, konjugiert Komplexe berechnen etc.

In [75]:
A.getT() #Transponierte Matrix

matrix([[1, 3],
        [2, 4]])

### Aufgabe 6:  

- Definieren Sie sich zwei Arrays und bilden Sie deren Produkt. Gibt es einen Unterschied zum Ergebnis, wenn Sie die beiden Arrays als Matrix definieren und dann das Produkt bilden?


## 2.4) Zugriff auf Elemente von Matrizen und Arrays

In [76]:
A = np.matrix('1 2 3 4 5; 6 7 8 9 10') #Definiere Matrix im R^2
B = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]) #Definiere die gleiche Matrix als Array

In [77]:
A[0,1] #zweites Element in der ersten Zeile - Achtung: Zählung beginnt immer bei 0!!!

2

In [78]:
print (A[0,:]) #alle Elemente der ersten Zeile
print (A[1,:])  #alle Elemente der zweiten Zeile
print (A[:,0])  #alle Elemente der ersten Spalte
print (A[0,2:4]) #Elemente 3 bis 4 - rechte Intervallgrenze ausgeschlossen!

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[[1]
 [6]]
[[3 4]]


In [79]:
print (B[0,2:5]) #analog gilt alles auch für arrays

[3 4 5]


In [80]:
C = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18,19, 20]]) #Def. größeres Array C
print (C[1:4,2:5]) #Teilmengen können leicht herausgeschrieben werden

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


# 3) Lineare Algebra mit NumPy  

NumPy ist in der Lage viele verschiedene Operationen mit Arrays (Matrizen) auszuführen. Beispiele sind:  
- Determintante berechnen
- Inverse berechnen
- Cholesky-Zerlegung berechnen
- Lineare GSe lösen 
- ...  

Dazu wird das NumPy Paket "linalg" verwendet...

In [81]:
a = np.array([[1, 2], [3, 4]]) #2x2 Matrix: Det(A)=ad-bc 
np.linalg.det(a)

-2.0000000000000004

In [82]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ]) #mehrere ineinander verschachtelte Matrizen
a.shape 
np.linalg.det(a)

array([-2., -3., -8.])